<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1620198229750' stop='1620198232618'>
    <name>Factory</name>
    <title>Factory</title>
    <test-cases>
        <test-case start='1620198229751' status='failed' stop='1620198232618'>
            <name>creates a bulksale</name>
            <title>creates a bulksale</title>
            <labels>
                <label name='severity' value='critical'/>
                <label name='story' value=''/>
            </labels>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>TypeError: Found non-callable @@iterator</message>
                <stack-trace>TypeError: Found non-callable @@iterator
                    at Object.&lt;anonymous> (/Users/0xmotoko/code/bulksale/test/helper.ts:24:36)
                    at Generator.next (&lt;anonymous>)
                    at fulfilled (/Users/0xmotoko/code/bulksale/test/helper.ts:5:58)
                    at processTicksAndRejections (internal/process/task_queues.js:93:5)</stack-trace>
            </failure>
            <description type='text'></description>
        </test-case>
    </test-cases>
</ns2:test-suite>